-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 12:22:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `tipo_documento` VARCHAR(30) NOT NULL,
  `numero_documento` VARCHAR(25) NOT NULL,
  `edad` SMALLINT(2) NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colaborador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`colaborador` (
  `nombre_colaborador` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `nivel_acceso` SMALLINT(3) NOT NULL,
  `fecha_creación` DATE NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`nombre_colaborador`),
  INDEX `fk_colaborador_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_colaborador_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stock` VARCHAR(45) NOT NULL,
  `ingreso` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `precio` INT NOT NULL,
  `inventario_id` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productos_inventario1_idx` (`inventario_id` ASC) VISIBLE,
  INDEX `fk_productos_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_inventario1`
    FOREIGN KEY (`inventario_id`)
    REFERENCES `mydb`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(25) NOT NULL,
  `numero_documento` VARCHAR(25) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `colaborador_nombre_colaborador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_colaborador1_idx` (`colaborador_nombre_colaborador` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_colaborador1`
    FOREIGN KEY (`colaborador_nombre_colaborador`)
    REFERENCES `mydb`.`colaborador` (`nombre_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `colaborador_nombre_colaborador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_factura_productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_factura_colaborador1_idx` (`colaborador_nombre_colaborador` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_colaborador1`
    FOREIGN KEY (`colaborador_nombre_colaborador`)
    REFERENCES `mydb`.`colaborador` (`nombre_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
